### ISSUE TITLE
Meldung: Nachricht versendet, aber Infomail fehlgeschlagen ,error

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#28]
I don't get an email, when I create new in module mailbox.
I work with cb and uddeIM in joomla 5 with cb and joomla modules
Even with debung, I don't get more infos.

**Comment by joomod** [comment]
that's an issue we are orking on...
(see https://github.com/slabbi/uddeIM/issues/14 )

first check all config AND user settings
(the message system about email noticication is not complete,
as it is part of some new settings to find the eror)
the main problem is that from mail() function there is only true or false response

**Comment by slabbi** [comment]
Please note that php mail does only work when a correct username and email syntax is used. When I remember correctly there was a problem on some systems when the sender name contains a space. Please try "Webmaster" or something similar as sender name.

The boolean return value is fine since a message could be added in the caller, e.g.:

```
		if(uddeIMsendmail($config->emn_sendername, $config->emn_sendermail, $var_toname, $var_tomail, $subject, $var_body, $replyto, $replytoname, "", $config)) {
			// maybe a code here that the email cound not have been sent
		}
```

**Comment by jojo12** [comment]
I installed the simple notifier with the changed helper.php
and now I get emails.
Yeah, you seem to go in the right direction!

**Comment by joomod** [comment]
hmm, I didn't see a depence on simple notifier, but I will test the opposite
as I have installed too.
testing on the site of the other user I found that there are still some J5 errors
(may be strict on 5.01 - I don't know)
basicly the are old config calls, which leads to an error message in the mail function
(Factory::getConfig()  **must be**  Factory::getApplication()->getConfig();)
so I changed all and in addition the script and style loading commends from
old $document to the new Webasset()
so I'm testing this right now.
(don't know about your email header?)

**Comment by jojo12** [comment]
I don't know why it works now, the only thing I changed today was the helper in simple notifier. But perhaps it was ok but didn't remarked it because of cache?
Now it works best: i replaced Messaging with the email of the site. But I don't succeed to bring it from the SPAM folder to the INBOX.
And it works well together with CB and uddeIM
Thanks a lot, excellent!!!

**Comment by joomod** [comment]
Spam or not only depends on the data in the header.
normally, if you give a good name and a good return address it should work.
(btw. I test what Slabbi said, and it doesn't effect badly, even if i leave the Oranization blank,
the omly required is a valid return address)

**Comment by jojo12** [comment]
BTW: is it possible to activate the labels, to easier declare the issues?

Jojo12

 

Von: joomod ***@***.*** 
Gesendet: Montag, 8. Januar 2024 21:44
An: slabbi/uddeIM
Cc: jojo12; Author
Betreff: Re: [slabbi/uddeIM] Meldung: Nachricht versendet, aber Infomail fehlgeschlagen ,error (Issue #28)

 

Spam or not only depends on the data in the header.
normally, if you give a good name and a good return address it should work.
(btw. I test what Slabbi said, and it doesn't effect badly, even if i leave the Oranization blank,
the omly required is a valid return address)

**Comment by slabbi** [comment]
> Spam or not only depends on the data in the header.

My post was related to the issue that a message cannot be sent.
The mail() command may fail when the username or sender email is not correct (some systems may have problems when the username contains a space). It does not affect receiving emails. If you are not receiving emails from your web server, the problem is most likely because the host is blacklisted somewhere. This is why MTA and web server are usually not on the same server.
