### ISSUE TITLE
error when activating statistic module uddeIM5 for Joomla 5.0.3

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#36]
Unsupported operand types: string + int

(I don't need this module, but better to post this item)

**Comment by joomod** [comment]
I see and found.
just add (int) to **(int)**$uddmosConfig_offset 
(this is the main joomla system offset and returns a string if empty)
(corrected in next upload)

**Comment by jojo12** [comment]
yes, that's it, thanks

**Comment by joomod** [comment]
**that was wrong**:  (would always use 0 as joomla value because this just return a sting for timezones)
**we must add** this two lines: (instead of $uddmosConfig_offset = uddeIMgetOffset())
$timezone = new \DateTimeZone(uddeIMgetOffset());
$uddmosConfig_offset = $timezone->getOffset(new \DateTime)/3600;  (returns int)
(int) therefore is no longer needed
