### ISSUE TITLE
warning in a english uddeIM:

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#67]
After installing i got:
​
​
Warning: Constant _UDDEADM_MAILSYSTEM_EXP already defined in C:\xampp\htdocs\joomla\administrator\components\com_uddeim\language\english.php on line 827

**Comment by slabbi** [comment]
It is twice in french.php. Fixed there.
Don't see it multiple times in other files.

**Comment by slabbi** [comment]
Sorry, was also in english.php twice.

**Comment by slabbi** [comment]
I created a batch to keep the language files in sync:
TRANSLATIONS/language.utf8/*
This could also be used to keep the files using a local character code table and UTF-8 for uddeIM 5.x in sync.
Currently it seems that all language files are not longer in sync with the German and English language file.

Since this bug is fixed -> closed
